version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Prevents overwriting node_modules on bind mount
    environment:
      - NODE_ENV=development
    command: npm run dev
